version: '3.9'

services:
  db:
    image: postgis/postgis:15-3.3-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: root
      POSTGRES_DB: app_dev
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5436:5432'
  api:
    build: .
    ports:
      - '8000:8000'
    env_file:
      - .env.dev
    restart: unless-stopped

    depends_on:
      - db

volumes:
  data:
